-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "saleAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "amountReceived" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "customerChange" SET DEFAULT 0,
ALTER COLUMN "customerChange" SET DATA TYPE DOUBLE PRECISION;
