export const tableData = [
  {
    employee_id: '123456',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    status: 'active',
    phone_number: '+509 39309079',
    position: 'Software Engineer',
    shift: '09:00 AM - 05:00 PM',
  },
  {
    employee_id: '123457',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    status: 'inactive',
    phone_number: '39309079',
    position: 'Product Manager',
    shift: '10:00 AM - 06:00 PM',
  },
  {
    employee_id: '123458',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    status: 'on_leave',
    phone_number: '39309079',
    position: 'Product Manager',
    shift: '10:00 AM - 06:00 PM',
  },
  {
    employee_id: '123459',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    status: 'inactive',
    phone_number: '39309079',
    position: 'Product Manager',
    shift: '10:00 AM - 06:00 PM',
  },
];
